server:
  port: 8081

---
server:
  port: 8083
spring:
  profiles: dev

person:
  lastName: hello
  age: 18
  boss: false
  birth: 2017/12/12
  maps: {k1: v1,k2: 12}
  lists:
    ‐ lisi
    ‐ zhaoliu
dog:
  name: 小狗
  age: 12